# Tomcat settings
server:
  port: ${TOMCAT_PLAT_PORT:9080}
  servlet:
    context-path: /
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
    basedir: ./

# Spring settings
spring:
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: ${HTTP_MULTIPART_MAX_FILE_SIZE:100MB}
      max-request-size: ${HTTP_MULTIPART_MAX_REQUEST_SIZE:100MB}
  messages:
    basename: i18n/tips,i18n/validates
    cache-duration: 86400
    encoding: UTF-8

# Incarcloud settings
incarcloud:
  swagger2:
    api:
      title: 英卡SB2示例项目在线API文档（APP端）
      description: 本文档包含手机端全部业务接口，注意保密。
      service-url: http://localhost:9080/doc.html
      version: 0.4.2-SNAPSHOT
  auth:
    jwt:
      secret-key: A3MZkHTQ6db/kOP6Q3F3IGmXTfES9BUIN0PHfnG8uCY=
      token-header-name: x-access-token
      token-expired-seconds: 7*24*60*60
