# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:9090}
  servlet:
    context-path: /
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
    basedir: ./

# Spring settings
spring:
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: ${HTTP_MULTIPART_MAX_FILE_SIZE:100MB}
      max-request-size: ${HTTP_MULTIPART_MAX_REQUEST_SIZE:100MB}
  messages:
    basename: i18n/tips,i18n/validates
    cache-duration: 86400
    encoding: UTF-8

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      incarcloud: DEBUG
    io:
      sparrow: INFO
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: plat.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}

# Incarcloud settings
incarcloud:
  swagger2:
    api:
      title: 英卡SB2示例项目在线API文档（平台端）
      description: 本文档包含平台端全部业务接口，注意保密。
      service-url: http://localhost:9080/doc.html
      version: 1.0-Milestone
  ## 业务配置
  biz:
    tag: plat
  pay: # 第三方支付
    alibaba: # 支付宝
      appId: yourappid
      appPrivateKey: yourappprivatekey
      alipayGatewayUrl: youralipaygatewayurl
      alipayPublicKey: youralipaypublickey
      callbackNotifyUrl: yourcallbacknotifyurl
      webReturnUrl: yourwebreturnurl
    weixin: # 微信支付
      appId: yourappid
      mchId: yourmchid
      apiSecret: yourapisecret
      # cat apiclient_cert.p12 | base64 -w 0
      apiPkcs12Cert: yourapipkcs12cert
      apiDomainString: yourdomainString
      notifyUrl: yournotifyUrl
